name: CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Which platform to build for?'
        required: true
        type: choice
        default: all
        options:
          - ios
          - android
          - all
  pull_request:
    branches:
      - main
      - dev

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.HABITLY_EXPO }}
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Compile'
        run: ./build.cmd Compile
